name: Deploy To EC2

on:
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Build Docker Image And Upload TO ECR" ]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    permissions:
      id-token: write
      contents: read
    
    defaults:
      run: 
        working-directory: terraform

    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v3
      
      - name: Debug
        run: echo OIDC = ${{ secrets.AWS_ROLE_OIDC }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        id: init
        run: |
          terraform fmt
          terraform init -upgrade
  
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
